name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu

    steps:
    - name: Checar o código do repositório
      uses: actions/checkout@v3

    # Instalar Docker e Docker Compose
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Instalar Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y curl
        curl -L https://github.com/docker/compose/releases/download/v2.17.0/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version  # Verifica se o docker-compose foi instalado corretamente
    
    # Instalar dependências do backend
    - name: Instalar dependências do backend
      run: |
        cd api  # Entrar no diretório 'api' se o package.json está lá
        npm install
    
    # Instalar dependências do frontend (se necessário)
    - name: Instalar dependências do frontend
      run: |
        cd blog-frontend  # Entrar no diretório 'blog-frontend' se necessário
        npm install

    # Construir as imagens Docker
    - name: Construir as imagens Docker
      run: |
        docker-compose -f docker-compose.yml build  # Isso irá construir as imagens definidas no docker-compose.yml
    
    # Rodar os testes com Docker
    - name: Rodar os testes com Docker
      run: |
        docker-compose -f docker-compose.yml up -d
        docker-compose -f docker-compose.yml exec api npm test  # Executar testes dentro do container 'api'
        docker-compose -f docker-compose.yml down  # Parar os containers
    
    # Deploy no Docker Hub com uma tag personalizada
    - name: Deploy no Docker Hub
      run: |
        echo "Realizando deploy para o Docker Hub..."
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        # Tag da imagem com a tag personalizada (substitua 'tagname' com a tag desejada, ex: 'v1.0')
        docker tag blog-api:latest ${{ secrets.DOCKER_USERNAME }}/blog-professores:${{ github.sha }}  # Usando o hash do commit como tag
        # Enviar a imagem para o Docker Hub
        docker push ${{ secrets.DOCKER_USERNAME }}/blog-professores:${{ github.sha }}
    env:
      MONGODB_URI: ${{ secrets.MONGODB_URI }}  # Usando a secret do MongoDB URI
