name: CI/CD Pipeline

on:
  push:
    branches:
      - fase_03 #main
  pull_request:
    branches:
      - fase_03 #main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checar o código do repositório
      uses: actions/checkout@v3

    # Instalar Docker e Docker Compose
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Instalar Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y curl
        curl -L https://github.com/docker/compose/releases/download/v2.17.0/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version  # Verifica se o docker-compose foi instalado corretamente
    
    # Instalar dependências do backend
    - name: Instalar dependências do backend e testar
      run: |
        cd api  # Entrar no diretório 'api' se o package.json está lá
        npm install
        npm test
    
    # Instalar dependências do frontend 
    - name: Instalar dependências do frontend
      run: |
       cd frontend  
       npm install
    # Construir e empurrar as imagens Docker
    - name: Construir e empurrar as imagens Docker
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker-compose -f docker-compose.yml build
        docker-compose -f docker-compose.yml push

    # Iniciar serviços Docker para testes
    - name: Iniciar serviços Docker
      run: |
        docker-compose -f docker-compose.yml up -d

    # Verificar estado do MongoDB
    - name: Verificar estado do MongoDB
      run: |
        docker ps -a
        docker logs blog-mongodb
